{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Свободное место на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\nnode_filesystem_avail_bytes{mountpoint=\"/\"}\n/\nnode_filesystem_size_bytes{mountpoint=\"/\"}\n) * 100",
     "legendFormat": "Free Disk Space, GiB"
    }
   ]
  },
  {
   "title": "Загрузка процессора",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n) * 100)",
     "legendFormat": "CPU Utilization (%)"
    }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024^3",
     "legendFormat": "Free Memory,  GiB"
    }
   ]
  },
  {
   "title": "Средняя нагрузка системы",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU Load Average - 1min" },
    { "expr": "node_load5", "legendFormat": "CPU Load Average - 5min" },
    { "expr": "node_load15", "legendFormat": "CPU Load Average - 15 min" }
   ]
  }
 ]
}